### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by gotzmann** [rryqszq4/ngx_php#32]
Great module! Really impressed with Techempower Benchamark results.
I would like to know - is it ready to use in production? 
Can I plug this thing into Symfony project? 
Are there speed / memory benefits over Road Runner server for PHP?

**Comment by rryqszq4** [comment]
@gotzmann 
Thanks for the attention to the project, ngx_php has not yet released a stable version, there are still a lot of imperfections, but we have already used it in the company's internal projects. Because ngx_php is not a replacement for fpm, some traditional php frameworks should not support it, including Symfony.

**Comment by gotzmann** [comment]
OK, hope you'll keep working on module, would like to use it with lua_nginx simultaneously on the same Nginx instance.

**Comment by rryqszq4** [comment]
@gotzmann 
Thanks, If you have time, you can try it out. And ngx_lua is the best. 
haha
